name: Installation test after page deployment

on:
  # Run after a new version is deployed
  pages:
    types: [deploy]

  # On demand
  workflow_dispatch:

jobs:
  post_deploy_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
      - name: Install public-hello
        run: |
          python -m pip install --upgrade pip
          pip install public-hello --extra-index-url https://astariul.github.io/github-hosted-pypi/

          # Check if the package and its dependency was installed
          pip show public-hello
          pip show mydependency

          # The code from the package should be accessible
          python -c "from public_hello import hi; assert hi() == 'Hello world from public repository (with a dependency)'"
      - name: Install public-hello older version
        run: |
          python -m pip install --upgrade pip
          pip install public-hello==0.1 --extra-index-url https://astariul.github.io/github-hosted-pypi/

          # Check if the package was installed
          pip show public-hello

          # The code from the package should be accessible
          python -c "from public_hello import hi; assert hi() == 'Hello world from public repository'"
